CREATE TABLE IF NOT EXISTS DELIVERIES(
    DELIVERY_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT VARCHAR(100),
    SUPPLIER VARCHAR(100),
    QUANTITY INT,
    EXPECTED_DATE VARCHAR(100),
    EXPECTED_WAREHOUSE VARCHAR(100),
    RECEIVED bit
);